export type PhaseId = 1 | 2 | 3 | 4;

export type AndragogySkill = {
  id: string;
  title: string;
  week: number;
  phase: PhaseId;
  required: boolean;
  skippable: boolean;
  gate: boolean;
  prereqs: string[];
  tags: string[];
};

export const SKILLS: AndragogySkill[] = [
  {
    id: "adult-learning-foundations",
    title: "Adult Learning Foundations",
    week: 1,
    phase: 1,
    required: true,
    skippable: false,
    gate: false,
    prereqs: [],
    tags: ["knowles", "andragogy", "assumptions", "learner-context"],
  },
  {
    id: "adult-experience-readiness",
    title: "Adult Experience and Readiness",
    week: 2,
    phase: 1,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["adult-learning-foundations"],
    tags: ["experience", "readiness", "identity", "prior-knowledge"],
  },
  {
    id: "experiential-reflection",
    title: "Experiential and Reflective Learning",
    week: 3,
    phase: 1,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["adult-experience-readiness"],
    tags: ["kolb", "reflection", "practice", "feedback"],
  },
  {
    id: "phase-1-foundations-gate",
    title: "Phase 1 Foundations Gate",
    week: 4,
    phase: 1,
    required: true,
    skippable: false,
    gate: true,
    prereqs: ["adult-learning-foundations", "adult-experience-readiness", "experiential-reflection"],
    tags: ["gate", "audit", "redesign", "foundation-analysis"],
  },
  {
    id: "motivation-design",
    title: "Adult Motivation Design",
    week: 5,
    phase: 2,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["phase-1-foundations-gate"],
    tags: ["motivation", "wlodkowski", "relevance", "confidence"],
  },
  {
    id: "self-direction-coaching",
    title: "Self-Directed Learning Coaching",
    week: 6,
    phase: 2,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["motivation-design"],
    tags: ["self-direction", "grow", "learning-contracts", "agency"],
  },
  {
    id: "transformative-critical-reflection",
    title: "Transformative and Critical Reflection",
    week: 7,
    phase: 2,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["self-direction-coaching", "experiential-reflection"],
    tags: ["mezirow", "brookfield", "critical-reflection", "ethics"],
  },
  {
    id: "phase-2-agency-gate",
    title: "Phase 2 Agency Gate",
    week: 8,
    phase: 2,
    required: true,
    skippable: false,
    gate: true,
    prereqs: ["motivation-design", "self-direction-coaching", "transformative-critical-reflection"],
    tags: ["gate", "motivation", "self-direction", "advising"],
  },
  {
    id: "needs-outcomes-analysis",
    title: "Needs and Outcomes Analysis",
    week: 9,
    phase: 3,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["phase-2-agency-gate"],
    tags: ["needs-assessment", "task-analysis", "outcomes", "performance"],
  },
  {
    id: "adult-program-design",
    title: "Adult Program Design",
    week: 10,
    phase: 3,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["needs-outcomes-analysis"],
    tags: ["practice", "scenario", "feedback", "transfer"],
  },
  {
    id: "adult-facilitation-evaluation",
    title: "Adult Facilitation and Inclusion",
    week: 11,
    phase: 3,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["adult-program-design", "transformative-critical-reflection"],
    tags: ["facilitation", "inclusion", "udl", "learning-community"],
  },
  {
    id: "phase-3-design-facilitation-gate",
    title: "Phase 3 Design and Facilitation Gate",
    week: 12,
    phase: 3,
    required: true,
    skippable: false,
    gate: true,
    prereqs: ["needs-outcomes-analysis", "adult-program-design", "adult-facilitation-evaluation"],
    tags: ["gate", "evaluation", "rubric", "blueprint"],
  },
  {
    id: "expert-consulting",
    title: "Expert Diagnosis and Consulting",
    week: 13,
    phase: 4,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["phase-3-design-facilitation-gate"],
    tags: ["consulting", "diagnosis", "ethics", "stakeholders"],
  },
  {
    id: "research-informed-improvement",
    title: "Research-Informed Improvement",
    week: 14,
    phase: 4,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["expert-consulting"],
    tags: ["research", "evaluation", "measurement", "improvement"],
  },
  {
    id: "capstone-portfolio",
    title: "Capstone Portfolio and Productization",
    week: 15,
    phase: 4,
    required: true,
    skippable: false,
    gate: false,
    prereqs: ["expert-consulting", "research-informed-improvement"],
    tags: ["portfolio", "writing", "product", "toolkit"],
  },
  {
    id: "expert-gate",
    title: "Expert Gate and Capstone Defense",
    week: 16,
    phase: 4,
    required: true,
    skippable: false,
    gate: true,
    prereqs: ["capstone-portfolio", "research-informed-improvement", "phase-1-foundations-gate", "phase-2-agency-gate", "phase-3-design-facilitation-gate"],
    tags: ["gate", "expert", "capstone", "defense"],
  },
];
